apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello
  namespace: hello-namespace
spec:
  secretName: hello
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
  - 'shop.anand.contact'
  - 'blog.anand.contact'